### ISSUE TITLE
Dependency on net 5

### ISSUE THREAD

**Issue by whann0205** [xaviersolau/BlazorJsonLocalization#10]
Is it possible to make Version not dependent on net 5.0 to
be compatible with Version 3.1? For Example .netstandard 2.1?

**Comment by xaviersolau** [comment]
Hello thanks for asking :-)

It should be possible to make a netstandard  2.1 package.... at least for the main SoloX.BlazorJsonLocalization project!

What is your use case exactly? Do you also use the SoloX.BlazorJsonLocalization.ServerSide and or the SoloX.BlazorJsonLocalization.WebAssembly extension projects as well?

**Comment by whann0205** [comment]
Right now i am working on a project based on mobile blazor bindings,
so i dont really know if its more webassembly or serverside since that one is based on xamarin forms. 
I tried to move to net maui but there always too much bugs to migrate 
to it. So i am stuck with .net 3.1 and bindings ...
Yesterday i found
https://github.com/jsakamoto/Toolbelt.Blazor.I18nText.
Maybe thats easier for me to use since bindings seems to be
buggy with resx files...
It try with that first thank you for your answer, i hope i can ask you again if 
i fail to use that one.
But would it be a lot of work?

**Comment by xaviersolau** [comment]
Actually, I don't think this is a lot of work. I will have a look this WE but in the worst case I will need to split the project.

**Comment by xaviersolau** [comment]
I have published a package that is compatible with Net Standard 2.1 and Net Core 3.1.
Here it is: https://www.nuget.org/packages/SoloX.BlazorJsonLocalization/1.0.1-alpha.1

It would be very kind if you could try it and let me know if it solved your compatibility issue.

**Comment by whann0205** [comment]
Just to give a quick answer. Have downloaded and installed that one without any errors. 
Tried a quick setup but failed maybe because i choose the wrong folder structure. 
That https://github.com/dotnet/MobileBlazorBindings structure is not really clearly understandable
for me. Question is where to put that Resources folder ?

**Comment by xaviersolau** [comment]
I wrote an article explaining how to use the lib:
https://medium.com/younited-tech-blog/how-to-use-blazorjsonlocalizer-a0bb3fc4b48c

but basically let's say that you've got:
a project: 'MyProject'
a project folder: 'MyFolder'
and in the folder a component: 'MyComponent'

Giving us this file structure:
MyProject/MyFolder/MyComponent.cs

In that case you can put the localization files mapped on this structure:
MyProject/Resources/MyFolder/MyComponent.json
MyProject/Resources/MyFolder/MyComponent-fr.json
MyProject/Resources/MyFolder/MyComponent-de.json

and you can setup the localizer services with:
```csharp
services.AddServerSideJsonLocalization(
    builder =>
    {
        builder.UseEmbeddedJson(options =>
        {
            options.ResourcesPath = "Resources";
        });
    });
```

finally make sure that your json resources files are registered as EmbeddedResource.

I hope this help...

**Comment by whann0205** [comment]
Your articles are superb also your explainations, but it still does not work.

If i take a look at the debug log i see:
**[0:] SoloX.BlazorJsonLocalization.Services.Impl.EmbeddedJsonLocalizationExtensionService: Warning: Embedded File Resources/WebUI/Pages/Index-en.json does not exist**

![ProjectFolders](https://user-images.githubusercontent.com/71807453/135898631-7e7aa181-1fd9-4a6b-ba9d-4740a4ee2c11.PNG)

In this screenshot you see that the file is here. Maybe again the wrong folder??

**Comment by xaviersolau** [comment]
Ok from what I can see in your solution, your 'Resources' sub folder is in the 'wwwroot' folder. You can move it directly in your project folder:
from AssetQueryApp/wwwroot/Resources/WebUI/Pages/Index-en.json
to AssetQueryApp/Resources/WebUI/Pages/Index-en.json

And don't forget to set the EmbeddedResource on the json file properties.

like this:
![image](https://user-images.githubusercontent.com/15972064/135917186-e3818850-71af-429f-8ae9-9048c5b4a31c.png)

**Comment by whann0205** [comment]
Yep that does the trick. I was misinterpreting the mobile blazor bindings documentation about the bundling behavior with wwwroot.
Now everything works perfect!!!
Great component!
